export const validEmail = (inputEmail) => {
    emailRegex = new RegExp(/^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/);
    if (inputEmail.match(emailRegex)) {
        return true
    }
    return false
}

export const validPhoneNumber = (inputPhoneNumber) => {
    phoneNumberRegex = new RegExp(/^0[45]\d{8}$/);
    return inputPhoneNumber.match(phoneNumberRegex);
}

export const validDateTime = (inputDateTime) => {
    // Regex generated by Chat GPT
    // Prompt: Regex for hh:mm dd/mm/yyyy in js
    const dateTimeRegex = new RegExp(/^(0[0-9]|1[0-9]|2[0-3]):[0-5][0-9] (0[1-9]|1[0-9]|2[0-9]|3[0-1])\/(0[1-9]|1[0-2])\/\d{4}$/);

    if (!inputDateTime.match(dateTimeRegex)) {
        return false;
    }

    // Checks if date entered is valid in the case of leap years
    // Code generated by Chat GPT. Continuation from previous prompt
    // Prompt: Does it take leap years into cocnsideration?
    const parts = inputDateTime.split(" ");
    const datePart = parts[1];
    const [day, month, year] = datePart.split("/").map(Number);

    const date = new Date(year, month - 1, day);
    if (
        date.getFullYear() !== year ||
        date.getMonth() !== month - 1 ||
        date.getDate() !== day
    ) {
        console.log("leap year coi")
        return false; // Invalid date
    }

    return true;
}

export const validateCoordinates = (inputCoordinates) => {
    const coordinatesRegex = new RegExp(/^[-+]?(180(\.0+)?|((1[0-7]\d)|([1-9]?\d))(\.\d+)?),\s*[-+]?([1-8]?\d(\.\d+)?|90(\.0+)?)$/);
    return inputCoordinates.match(coordinatesRegex);
}