
name: CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events for the main branch
  push:
    branches: [main, add-automated-deployment]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  backend-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Deploy to Heroku
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: "src/backend"
        env:
          DATABASE_HOST: ${{secrets.DATABASE_HOST}}
          DATABASE_NAME: ${{secrets.DATABASE_NAME}}
          DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
          DATABASE_PORT: ${{secrets.DATABASE_PORT}}
          DATABASE_USER: ${{secrets.DATABASE_USER}}
