
name: CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events for the main branch
  push:
    branches: [main, add-automated-deployment]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  backend-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Deploy to Heroku
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: "src/backend"
        env:
          DATABASE_HOST: ${{secrets.DATABASE_HOST}}
          DATABASE_NAME: ${{secrets.DATABASE_NAME}}
          DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
          DATABASE_PORT: ${{secrets.DATABASE_PORT}}
          DATABASE_USER: ${{secrets.DATABASE_USER}}

  frontend-build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src/frontend/Finding-Neno

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
          cache-dependency-path: '**/package-lock.json'

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: 3.17.1
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm install

      # Build the preview of the app
      - name: Build preview application
        run: |
          eas secret:create --name GOOGLE_MAPS_API_KEY --value ${{ secrets.GOOGLE_MAPS_API_KEY }} --type string --force --non-interactive
          eas secret:create --name EAS_PROJECT_ID --value ${{ env.EAS_PROJECT_ID }} --type string --force --non-interactive
          eas build --profile preview --platform android --clear-cache --non-interactive
